# Generated by Django 5.2.4 on 2025-07-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
